    name: GitHub Classroom Workflow

    on: [push]
    
    env:
      GWIZ_TOKEN: ${{ secrets.GWIZ_TOKEN }}

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: education/autograding@v1
